# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import post_pb2 as post__pb2


class PostServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPostByID = channel.unary_unary(
                '/PostService/GetPostByID',
                request_serializer=post__pb2.PostIDRequest.SerializeToString,
                response_deserializer=post__pb2.Post.FromString,
                )
        self.Search = channel.unary_unary(
                '/PostService/Search',
                request_serializer=post__pb2.SearchText.SerializeToString,
                response_deserializer=post__pb2.PostsRespond.FromString,
                )


class PostServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPostByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPostByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostByID,
                    request_deserializer=post__pb2.PostIDRequest.FromString,
                    response_serializer=post__pb2.Post.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=post__pb2.SearchText.FromString,
                    response_serializer=post__pb2.PostsRespond.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PostService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPostByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PostService/GetPostByID',
            post__pb2.PostIDRequest.SerializeToString,
            post__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PostService/Search',
            post__pb2.SearchText.SerializeToString,
            post__pb2.PostsRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
