# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tag_pb2 as tag__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='post.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\npost.proto\x1a\ttag.proto\"e\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12 \n\x0bpost_status\x18\x04 \x01(\x0e\x32\x0b.PostStatus\x12\x12\n\x04tags\x18\x05 \x03(\x0b\x32\x04.Tag\"\x1b\n\rPostIDRequest\x12\n\n\x02id\x18\x01 \x01(\r\"$\n\x0cPostsRespond\x12\x14\n\x05posts\x18\x01 \x03(\x0b\x32\x05.Post\" \n\nSearchText\x12\x12\n\nsearch_key\x18\x01 \x01(\t*6\n\nPostStatus\x12\r\n\tNO_STATUS\x10\x00\x12\x0b\n\x07\x41\x43\x45PTED\x10\x01\x12\x0c\n\x08REJECTED\x10\x02\x32]\n\x0bPostService\x12&\n\x0bGetPostByID\x12\x0e.PostIDRequest\x1a\x05.Post\"\x00\x12&\n\x06Search\x12\x0b.SearchText\x1a\r.PostsRespond\"\x00\x62\x06proto3'
  ,
  dependencies=[tag__pb2.DESCRIPTOR,])

_POSTSTATUS = _descriptor.EnumDescriptor(
  name='PostStatus',
  full_name='PostStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_STATUS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACEPTED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REJECTED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=229,
  serialized_end=283,
)
_sym_db.RegisterEnumDescriptor(_POSTSTATUS)

PostStatus = enum_type_wrapper.EnumTypeWrapper(_POSTSTATUS)
NO_STATUS = 0
ACEPTED = 1
REJECTED = 2



_POST = _descriptor.Descriptor(
  name='Post',
  full_name='Post',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Post.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='Post.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='Post.body', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='post_status', full_name='Post.post_status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags', full_name='Post.tags', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=126,
)


_POSTIDREQUEST = _descriptor.Descriptor(
  name='PostIDRequest',
  full_name='PostIDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PostIDRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=155,
)


_POSTSRESPOND = _descriptor.Descriptor(
  name='PostsRespond',
  full_name='PostsRespond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='posts', full_name='PostsRespond.posts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=193,
)


_SEARCHTEXT = _descriptor.Descriptor(
  name='SearchText',
  full_name='SearchText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='search_key', full_name='SearchText.search_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=227,
)

_POST.fields_by_name['post_status'].enum_type = _POSTSTATUS
_POST.fields_by_name['tags'].message_type = tag__pb2._TAG
_POSTSRESPOND.fields_by_name['posts'].message_type = _POST
DESCRIPTOR.message_types_by_name['Post'] = _POST
DESCRIPTOR.message_types_by_name['PostIDRequest'] = _POSTIDREQUEST
DESCRIPTOR.message_types_by_name['PostsRespond'] = _POSTSRESPOND
DESCRIPTOR.message_types_by_name['SearchText'] = _SEARCHTEXT
DESCRIPTOR.enum_types_by_name['PostStatus'] = _POSTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Post = _reflection.GeneratedProtocolMessageType('Post', (_message.Message,), {
  'DESCRIPTOR' : _POST,
  '__module__' : 'post_pb2'
  # @@protoc_insertion_point(class_scope:Post)
  })
_sym_db.RegisterMessage(Post)

PostIDRequest = _reflection.GeneratedProtocolMessageType('PostIDRequest', (_message.Message,), {
  'DESCRIPTOR' : _POSTIDREQUEST,
  '__module__' : 'post_pb2'
  # @@protoc_insertion_point(class_scope:PostIDRequest)
  })
_sym_db.RegisterMessage(PostIDRequest)

PostsRespond = _reflection.GeneratedProtocolMessageType('PostsRespond', (_message.Message,), {
  'DESCRIPTOR' : _POSTSRESPOND,
  '__module__' : 'post_pb2'
  # @@protoc_insertion_point(class_scope:PostsRespond)
  })
_sym_db.RegisterMessage(PostsRespond)

SearchText = _reflection.GeneratedProtocolMessageType('SearchText', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHTEXT,
  '__module__' : 'post_pb2'
  # @@protoc_insertion_point(class_scope:SearchText)
  })
_sym_db.RegisterMessage(SearchText)



_POSTSERVICE = _descriptor.ServiceDescriptor(
  name='PostService',
  full_name='PostService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=285,
  serialized_end=378,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPostByID',
    full_name='PostService.GetPostByID',
    index=0,
    containing_service=None,
    input_type=_POSTIDREQUEST,
    output_type=_POST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='PostService.Search',
    index=1,
    containing_service=None,
    input_type=_SEARCHTEXT,
    output_type=_POSTSRESPOND,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSTSERVICE)

DESCRIPTOR.services_by_name['PostService'] = _POSTSERVICE

# @@protoc_insertion_point(module_scope)
