# Generated by Django 3.2.4 on 2021-06-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('non_status', 'No status'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='non_status', max_length=10)),
                ('body', models.TextField()),
                ('tags', models.ManyToManyField(blank=True, to='core.Tag')),
            ],
        ),
    ]
